language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx
matrix:
  include:
  - rvm: jruby-19mode
    jdk: oraclejdk7
  - rvm: jruby-19mode
    jdk: openjdk7
before_install:
  - gem update --system
  - gem --version
allow_failures:
  - rvm: ruby-head
services:
  - mongodb
